name: Publish Docs

on:
  push:
    branches:
      - main
    tags:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - name: Deploy Docs
        run: |
          cd test-app
          pnpm ember deploy production
